### ISSUE TITLE
[feature]: a mode to show menu items without assigned shortcut (in order to set them with CustomShortcuts)

### ISSUE THREAD

**Issue by huyz** [Anze/KeyCluCask#66]
### Proposal

As I mentioned in #65, there's an awesome integration with CustomShortcuts to edit key bindings. However, it's not possible to assign key bindings for menu items that don't already have one.

So I propose another toggle to include menu items that don't already have a binding.  This would work great if #65 were implemented as we could then do the two steps: toggle to show the binding-less menu items, then edit with CustomShortcuts to create the very first key binding for that menu item.

### Alternatives

I just have to launch CustomShortcuts separately, find the right app, type in the name of the menu and assign a shortcut. A very tedious process.

**Comment by Anze** [comment]
Hey [huyz](https://github.com/huyz),
Thanks for the proposal. I've already implemented such functionality. However, it's not yet optimized and might interfere with the app's workflow, also enabling feature might have huge performance impact when used on the app with large amount of menu items (like browsers for example). If you're interested in trying it out, you'll need to launch the app from Terminal with next command:
```env KEYCLU_EXPERIMENTAL=true open /Applications/KeyClu.app```
You'll find the new option available in Settings -> Advanced. Additionally, it will be possible to toggle it conveniently with an icon on the command bar, which will apply changes on the next panel appearance.

As mentioned earlier, this feature is still in the development stage. I'd greatly appreciate any feedback you may have on its functionality and usability.

**Comment by huyz** [comment]
Thanks! I'll check it out

**Comment by huyz** [comment]
Hmm, the only experimental feature I see is `Make It Rainbow`. I can't see the new option

**Comment by Anze** [comment]
Option "Show all menu items [EXPERIMENTAL]" should be on top if you relaunched app correctly.

**Comment by huyz** [comment]
Yeah I've tried a half-dozen times. I still can't see anything new.

Btw, the quit button in the settings dialog seems to just act like the red close button at the top left: it only closes the settings, but not the background app.  Is that intentional?

**Comment by Anze** [comment]
If you click red button in the Settings window - it would just close window, but not close the app. You need to stop app completely: click "power" in Settings window or pick "Quit KeyClu" at the menu bar.

**Comment by huyz** [comment]
That's what I mean: clicking the "power" button in Settings window doesn't quit the app completely. It just acts like the red button.  So I guess it's a bug

**Comment by Anze** [comment]
Not sure, which os you have?

**Comment by huyz** [comment]
macOS 14.4.1 23E224 (Sonoma) MacBookPro18,2 (Apple M1 Max, arm64)

**Comment by Anze** [comment]
Can you confirm that you have not enabled "Silent Launch/Quit" option and also do not see fading crossed app logo when click "power" button?

**Comment by huyz** [comment]
Oh yes, I do have `Silent Launch/Quit` enabled.  Disabling makes the "Power" button work properly

And now the `Show all menu items [EXPERIMENTAL]` option appears.

Thanks!

**Comment by Anze** [comment]
Thanks for checking. I'll note to fix this issue.

**Comment by huyz** [comment]
Is there a way to completely disable the list of browser bookmarks?  I really have no use for that at all.

**Comment by Anze** [comment]
Unfortunately no, but you can limit those to minimum - 100.

**Comment by Anze** [comment]
Hey [huyz](https://github.com/huyz),
I've just released a new version. There is implemented #69. I guess it might be a solution for you.

**Comment by huyz** [comment]
Awesome!

This is the easiest way in the world to set macOS Keyboard Shortcuts.  This should be promoted far and wide; e.g. in reddit /r/mac :)
